# Generated by Django 4.1.2 on 2022-10-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('backend', models.BooleanField()),
                ('age', models.IntegerField()),
                ('bio', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
